name: Project checks

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  consensus-changelog:

    name: Changelog sanity check

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - uses: actions/checkout@v4
      with:
        path: 'this-pr'

    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.base.ref || github.event.merge_group.base_ref }}
        path: 'main'

    - run: CI=1 ./this-pr/scripts/ci/check-changelogs.sh main this-pr

  check-cabal-files:
    runs-on: ubuntu-latest

    steps:
    - name: Install Haskell
      uses: input-output-hk/actions/haskell@latest
      id: setup-haskell
      with:
        cabal-version: "3.10.1.0"

    - uses: actions/checkout@v4

    - name: Cabal check
      run: ./scripts/ci/check-cabal-files.sh

  check-release-badges:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check README badges
      run: |
        for f in $(find ouroboros-consensus* *sop* -type f -name "*.cabal"); do
          pkg=$(grep "^name: " $f | rev | cut -d' ' -f1 | rev)
          ver=$(grep "^version: " $f | rev | cut -d' ' -f1 | rev)
          echo "Checking badge for $pkg-$ver"
          grep "$(echo $pkg | sed 's/-/--/g')-$ver" README.md
        done
