name: Check HLint

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get -y install libtinfo5

    - name: 'Set up HLint'
      uses: rwe/actions-hlint-setup@v1
      with:
        version: 3.6.1

    - name: 'Run HLint'
      uses: rwe/actions-hlint-run@v2
